name: sage
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - pytorch-cuda=11.8
  - numpy=1.24.3
  - matplotlib=3.7.1
  - seaborn=0.12.2
  - scikit-learn=1.3.0
  - pandas=2.0.3
  - tqdm=4.65.0
  - jupyter=1.0.0
  - notebook=6.5.4
  - ipykernel=6.25.0
  - pip=23.1.2
  - pip:
    - umap-learn==0.5.3
    - plotly==5.15.0
    - tensorboard==2.13.0
    - pillow==10.0.0
    - opencv-python==4.8.0.74
